version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/back'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/front'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/shared'
    schedule:
      interval: 'monthly'
